/*==========================================================
 *                                                          
 *  version.h - version information for SFL                  
 *                                                          
 *  Should be the last file included in parent source program.
 *  This file is generated by Boom at configuration time.   
 *  Copyright (c) 1991-2003 iMatix Corporation
 *==========================================================*/

#undef  VERSION         /*  Scrap any previous definitions  */
#undef  PRODUCT         
#undef  COPYRIGHT       
#undef  BUILDDATE       
#undef  BUILDMODEL      
#define VERSION         "2.50"
#define PRODUCT         "SFL/2.50"
#define COPYRIGHT       "Copyright (c) 1991-2003 iMatix Corporation"
#define BUILDDATE       "2004/07/22 17:51:37"
#define BUILDMODEL      "Debug release for internal use only"
/*  Embed the version information in the resulting binary   */
char *sfl_version_start = "VeRsIoNsTaRt:sfl";
char *sfl_version = VERSION;
char *sfl_product = PRODUCT;
char *sfl_copyright = COPYRIGHT;
char *sfl_builddate = BUILDDATE;
char *sfl_buildmodel = BUILDMODEL;
char *sfl_version_end = "VeRsIoNeNd:sfl";
