/*==========================================================
 *                                                          
 *  version.h - version information for SMT                  
 *                                                          
 *  Should be the last file included in parent source program.
 *  This file is generated by Boom at configuration time.   
 *  Copyright (c) 1991-2003 iMatix Corporation
 *==========================================================*/

#undef  VERSION         /*  Scrap any previous definitions  */
#undef  PRODUCT         
#undef  COPYRIGHT       
#undef  BUILDDATE       
#undef  BUILDMODEL      
#define VERSION         "2.80"
#define PRODUCT         "SMT/2.80"
#define COPYRIGHT       "Copyright (c) 1991-2003 iMatix Corporation"
#define BUILDDATE       "2004/07/22 17:51:37"
#define BUILDMODEL      "Debug release for internal use only"
/*  Embed the version information in the resulting binary   */
char *smt_version_start = "VeRsIoNsTaRt:smt";
char *smt_version = VERSION;
char *smt_product = PRODUCT;
char *smt_copyright = COPYRIGHT;
char *smt_builddate = BUILDDATE;
char *smt_buildmodel = BUILDMODEL;
char *smt_version_end = "VeRsIoNeNd:smt";
