/*---------------------------------------------------------------------------*
 *  xisuper.d - LIBERO dialog data definitions for xisuper.c.                *
 *  Generated by LIBERO 2.4 on 22 Jul, 2004, 16:52.                          *
 *  Schema file used: smtschm.c.                                             *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define _LR_NULL_STATE                  -1
#define terminate_event                 -1
#define busy_event                      0
#define error_event                     1
#define exception_event                 2
#define not_busy_event                  3
#define ok_event                        4
#define shutdown_event                  5
#define _LR_STATE_after_init            0
#define _LR_STATE_have_alarm            1
#define _LR_STATE_ready_to_go           2
#define _LR_STATE_defaults              3
#define _LR_defaults_state              3


/*- Function prototypes and macros ------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

MODULE initialise_the_thread        (THREAD *thread);
MODULE sleep_for_an_hour_or_so      (THREAD *thread);
MODULE terminate_the_thread         (THREAD *thread);
MODULE check_whether_xitami_busy    (THREAD *thread);
MODULE check_whether_overdue        (THREAD *thread);
MODULE clean_up_temporary_files     (THREAD *thread);
MODULE clean_up_log_files           (THREAD *thread);

#define the_next_event              _the_next_event
#define the_exception_event         _the_exception_event
#define the_external_event          _the_external_event
#define exception_raised            _exception_raised
#define io_completed                _io_completed


/*- Static areas shared by all threads --------------------------------------*/

static word _LR_nextst [4][6] =
{
    { 0,0,0,0,1,0 },
    { 0,0,0,0,2,0 },
    { 1,0,0,1,0,0 },
    { 0,0,2,0,0,3 }
};

static word _LR_action [4][6] =
{
    { 0,2,0,0,1,0 },
    { 0,0,0,0,3,0 },
    { 4,0,0,5,0,0 },
    { 0,0,6,0,0,2 }
};

static word _LR_offset [] =
{
    0,
    0,
    2,
    4,
    6,
    9,
    13
};

static word _LR_vector [] =
{
    0,_LR_STOP,
    1,_LR_STOP,
    2,_LR_STOP,
    3,0,_LR_STOP,
    4,5,0,_LR_STOP,
    0,2,_LR_STOP
};

static HOOK *_LR_module [6] = {
    sleep_for_an_hour_or_so,
    terminate_the_thread,
    check_whether_xitami_busy,
    check_whether_overdue,
    clean_up_temporary_files,
    clean_up_log_files
};

#if (defined (DEBUG))
static char *_LR_mname [6] =
{
     "Sleep-For-An-Hour-Or-So",
     "Terminate-The-Thread",
     "Check-Whether-Xitami-Busy",
     "Check-Whether-Overdue",
     "Clean-Up-Temporary-Files",
     "Clean-Up-Log-Files"
};

static char *_LR_sname [4] =
{
     "After-Init",
     "Have-Alarm",
     "Ready-To-Go",
     "Defaults"
};

static char *_LR_ename [6] =
{
     "Busy-Event",
     "Error-Event",
     "Exception-Event",
     "Not-Busy-Event",
     "Ok-Event",
     "Shutdown-Event"
};
#else
static char *_LR_mname [6] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5"
};

static char *_LR_sname [4] =
{
     "0",
     "1",
     "2",
     "3"
};

static char *_LR_ename [6] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5"
};
#endif
