/*---------------------------------------------------------------------------*
 *  xiadmin.d - LIBERO dialog data definitions for xiadmin.c.                *
 *  Generated by LIBERO 2.4 on 22 Jul, 2004, 16:52.                          *
 *  Schema file used: smtschm.c.                                             *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define _LR_NULL_STATE                  -1
#define terminate_event                 -1
#define accesslog_event                 0
#define advanced_event                  1
#define aliases_event                   2
#define back_event                      3
#define basehost_event                  4
#define cgi_event                       5
#define clear_event                     6
#define clear_logs_event                7
#define config_event                    8
#define console_event                   9
#define cycle_event                     10
#define cycle_logs_event                11
#define data_error_event                12
#define ddns_event                      13
#define default_event                   14
#define define_event                    15
#define define_dirs_event               16
#define define_users_event              17
#define delete_event                    18
#define details_event                   19
#define enter_event                     20
#define environment_event               21
#define errorlog_event                  22
#define errors_event                    23
#define exception_event                 24
#define exit_event                      25
#define filters_event                   26
#define first_event                     27
#define ftp_event                       28
#define ftperrors_event                 29
#define ftplog_event                    30
#define halt_event                      31
#define help_event                      32
#define hosts_event                     33
#define invert_event                    34
#define logging_event                   35
#define main_event                      36
#define messages_event                  37
#define mimes_event                     38
#define new_event                       39
#define new_session_event               40
#define next_event                      41
#define ok_event                        42
#define passwords_event                 43
#define refresh_event                   44
#define reshow_form_event               45
#define resource_event                  46
#define restart_event                   47
#define return_event                    48
#define save_event                      49
#define security_event                  50
#define select_config_event             51
#define select_resource_event           52
#define select_user_event               53
#define server_event                    54
#define serverlog_event                 55
#define show_event                      56
#define shutdown_event                  57
#define signoff_event                   58
#define signon_event                    59
#define ssi_event                       60
#define test_event                      61
#define timeout_event                   62
#define undo_event                      63
#define vhosts_event                    64
#define wizard_event                    65
#define wsx_event                       66
#define _LR_STATE_after_init            0
#define _LR_STATE_start_session         1
#define _LR_STATE_select_initial        2
#define _LR_STATE_main_menu             3
#define _LR_STATE_config_list           4
#define _LR_STATE_config_server         5
#define _LR_STATE_config_value_list     6
#define _LR_STATE_config_server_list    7
#define _LR_STATE_config_errors         8
#define _LR_STATE_config_ssi            9
#define _LR_STATE_config_ddns           10
#define _LR_STATE_config_advanced       11
#define _LR_STATE_config_cgi            12
#define _LR_STATE_config_cgi_sub_list   13
#define _LR_STATE_config_ftp            14
#define _LR_STATE_config_ftp_users      15
#define _LR_STATE_config_ftp_user       16
#define _LR_STATE_config_ftp_dirs       17
#define _LR_STATE_config_ftp_user_list  18
#define _LR_STATE_config_ftp_sub_list   19
#define _LR_STATE_config_security       20
#define _LR_STATE_config_resources      21
#define _LR_STATE_config_user_list      22
#define _LR_STATE_config_logging        23
#define _LR_STATE_config_log_file       24
#define _LR_STATE_console_panel         25
#define _LR_STATE_console_messages      26
#define _LR_STATE_console_config        27
#define _LR_STATE_connection_list       28
#define _LR_STATE_vhost_wizard          29
#define _LR_STATE_defaults              30
#define _LR_defaults_state              30


/*- Function prototypes and macros ------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

MODULE initialise_the_thread        (THREAD *thread);
MODULE decode_http_initial_request  (THREAD *thread);
MODULE determine_initial_screen     (THREAD *thread);
MODULE open_main_admin_menu         (THREAD *thread);
MODULE show_main_admin_menu         (THREAD *thread);
MODULE decode_http_request_reponse  (THREAD *thread);
MODULE use_defaults_config_name     (THREAD *thread);
MODULE load_current_config_file     (THREAD *thread);
MODULE open_config_server           (THREAD *thread);
MODULE show_config_server           (THREAD *thread);
MODULE dialog_call                  (THREAD *thread);
MODULE open_config_list             (THREAD *thread);
MODULE show_config_list_first       (THREAD *thread);
MODULE close_all_forms              (THREAD *thread);
MODULE open_vhost_wizard            (THREAD *thread);
MODULE show_vhost_wizard            (THREAD *thread);
MODULE check_config_list_livelink   (THREAD *thread);
MODULE close_current_form           (THREAD *thread);
MODULE dialog_return                (THREAD *thread);
MODULE show_config_list_next        (THREAD *thread);
MODULE use_basehost_config_name     (THREAD *thread);
MODULE cancel_current_config_file   (THREAD *thread);
MODULE update_config_server         (THREAD *thread);
MODULE save_current_config_file     (THREAD *thread);
MODULE show_config_server_defaults  (THREAD *thread);
MODULE open_config_aliases          (THREAD *thread);
MODULE show_config_value_list_first (THREAD *thread);
MODULE open_config_mimes            (THREAD *thread);
MODULE open_config_errors           (THREAD *thread);
MODULE show_config_errors           (THREAD *thread);
MODULE open_config_wsx              (THREAD *thread);
MODULE open_config_filter           (THREAD *thread);
MODULE open_config_ssi              (THREAD *thread);
MODULE show_config_ssi              (THREAD *thread);
MODULE open_config_ddns             (THREAD *thread);
MODULE show_config_ddns             (THREAD *thread);
MODULE open_config_advanced         (THREAD *thread);
MODULE show_config_advanced         (THREAD *thread);
MODULE open_config_vhosts           (THREAD *thread);
MODULE open_config_cgi              (THREAD *thread);
MODULE show_config_cgi              (THREAD *thread);
MODULE open_config_ftp              (THREAD *thread);
MODULE show_config_ftp              (THREAD *thread);
MODULE open_config_security         (THREAD *thread);
MODULE show_config_security         (THREAD *thread);
MODULE open_config_logging          (THREAD *thread);
MODULE show_config_logging          (THREAD *thread);
MODULE validate_config_value_list   (THREAD *thread);
MODULE update_config_value_list     (THREAD *thread);
MODULE clear_config_value_list      (THREAD *thread);
MODULE reshow_current_form          (THREAD *thread);
MODULE show_config_value_list_next  (THREAD *thread);
MODULE update_config_errors         (THREAD *thread);
MODULE show_config_errors_defaults  (THREAD *thread);
MODULE update_config_ssi            (THREAD *thread);
MODULE show_config_ssi_defaults     (THREAD *thread);
MODULE update_config_ddns           (THREAD *thread);
MODULE show_config_ddns_defaults    (THREAD *thread);
MODULE send_signon_to_ddns_agent    (THREAD *thread);
MODULE send_signoff_to_ddns_agent   (THREAD *thread);
MODULE update_config_advanced       (THREAD *thread);
MODULE show_config_advanced_defaults (THREAD *thread);
MODULE test_url_mapping             (THREAD *thread);
MODULE update_config_cgi            (THREAD *thread);
MODULE show_config_cgi_defaults     (THREAD *thread);
MODULE open_config_cgi_envir        (THREAD *thread);
MODULE open_config_cgi_alias        (THREAD *thread);
MODULE update_config_ftp            (THREAD *thread);
MODULE show_config_ftp_defaults     (THREAD *thread);
MODULE open_config_ftp_users        (THREAD *thread);
MODULE show_config_ftp_users_first  (THREAD *thread);
MODULE open_config_ftp_dirs         (THREAD *thread);
MODULE show_config_ftp_dirs_first   (THREAD *thread);
MODULE open_config_ftp_alias        (THREAD *thread);
MODULE check_ftp_users_livelink     (THREAD *thread);
MODULE open_config_ftp_user         (THREAD *thread);
MODULE show_config_ftp_user_new     (THREAD *thread);
MODULE cancel_config_resource_file  (THREAD *thread);
MODULE save_config_resource_file    (THREAD *thread);
MODULE show_config_ftp_users_next   (THREAD *thread);
MODULE show_config_ftp_users_same   (THREAD *thread);
MODULE show_config_ftp_user         (THREAD *thread);
MODULE update_config_ftp_user       (THREAD *thread);
MODULE delete_config_ftp_user       (THREAD *thread);
MODULE show_config_ftp_user_same    (THREAD *thread);
MODULE show_config_ftp_user_defaults (THREAD *thread);
MODULE show_config_ftp_user_first   (THREAD *thread);
MODULE set_permissions_as_chosen    (THREAD *thread);
MODULE show_config_ftp_user_next    (THREAD *thread);
MODULE check_ftp_dir_livelink       (THREAD *thread);
MODULE cancel_config_ftp_dir_file   (THREAD *thread);
MODULE save_config_ftp_dir_file     (THREAD *thread);
MODULE show_config_ftp_dirs_next    (THREAD *thread);
MODULE check_new_ftp_dir_name       (THREAD *thread);
MODULE open_config_ftp_user_list    (THREAD *thread);
MODULE show_config_ftp_dirs_same    (THREAD *thread);
MODULE update_config_ftp_user_list  (THREAD *thread);
MODULE update_config_security       (THREAD *thread);
MODULE show_config_security_defaults (THREAD *thread);
MODULE open_config_resources        (THREAD *thread);
MODULE show_config_resources_first  (THREAD *thread);
MODULE check_resources_livelink     (THREAD *thread);
MODULE update_config_resources      (THREAD *thread);
MODULE show_config_resources_next   (THREAD *thread);
MODULE check_new_resource_name      (THREAD *thread);
MODULE open_config_user_list        (THREAD *thread);
MODULE show_config_resources_same   (THREAD *thread);
MODULE update_config_user_list      (THREAD *thread);
MODULE update_config_logging        (THREAD *thread);
MODULE show_config_logging_defaults (THREAD *thread);
MODULE open_config_log_file         (THREAD *thread);
MODULE choose_server_log            (THREAD *thread);
MODULE show_log_file_details        (THREAD *thread);
MODULE choose_http_access_log       (THREAD *thread);
MODULE choose_http_error_log        (THREAD *thread);
MODULE choose_ftp_access_log        (THREAD *thread);
MODULE choose_ftp_error_log         (THREAD *thread);
MODULE update_log_file_details      (THREAD *thread);
MODULE show_log_file_format         (THREAD *thread);
MODULE show_log_file_defaults       (THREAD *thread);
MODULE cycle_log_file_if_possible   (THREAD *thread);
MODULE clear_log_file_if_possible   (THREAD *thread);
MODULE clear_console_panel_statistics (THREAD *thread);
MODULE show_console_panel           (THREAD *thread);
MODULE open_console_config          (THREAD *thread);
MODULE show_console_config          (THREAD *thread);
MODULE clear_all_active_logfiles    (THREAD *thread);
MODULE cycle_all_active_logfiles    (THREAD *thread);
MODULE open_console_messages        (THREAD *thread);
MODULE show_console_messages        (THREAD *thread);
MODULE open_connection_list         (THREAD *thread);
MODULE show_connection_list         (THREAD *thread);
MODULE clear_console_messages       (THREAD *thread);
MODULE invert_console_data          (THREAD *thread);
MODULE update_console_config        (THREAD *thread);
MODULE reload_server_base_config    (THREAD *thread);
MODULE show_console_config_defaults (THREAD *thread);
MODULE validate_vhost_definition    (THREAD *thread);
MODULE create_vhost_definition      (THREAD *thread);
MODULE send_resource_file_if_known  (THREAD *thread);
MODULE terminate_the_thread         (THREAD *thread);
MODULE check_simple_livelink        (THREAD *thread);
MODULE redirect_to_home_page        (THREAD *thread);
MODULE open_console_panel           (THREAD *thread);
MODULE restart_http_server_agent    (THREAD *thread);
MODULE shutdown_http_server_agent   (THREAD *thread);

#define the_next_event              _the_next_event
#define the_exception_event         _the_exception_event
#define the_external_event          _the_external_event
#define exception_raised            _exception_raised
#define io_completed                _io_completed


/*- Static areas shared by all threads --------------------------------------*/

static word _LR_nextst [31][67] =
{
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,4,0,0,3,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,29,0
    },
    { 0,0,0,4,5,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,4,0,0,0,0,0,0,4,0,0
     ,0,0,0,0,0,0,0,0,0,29,0,4,0,0,0,4,0,0,4,4,0,5,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0
    },
    { 0,11,7,5,0,12,0,0,0,0,0,0,0,10,5,0,0,0,0,0,0,0,0,8,0,0,7,0
     ,14,0,0,0,0,0,0,23,0,0,7,0,0,0,0,0,0,0,0,0,0,5,20,0,0,0,0,0
     ,0,0,0,0,9,0,0,5,6,0,7
    },
    { 0,0,0,6,0,12,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,14
     ,0,0,0,0,0,0,23,0,0,0,0,0,6,0,0,0,0,0,0,0,6,20,0,0,0,5,0,0,0
     ,0,0,0,0,0,6,6,0,0
    },
    { 0,0,0,5,0,12,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,14
     ,0,0,0,0,0,0,23,0,0,0,0,0,7,0,0,0,0,0,0,0,5,20,0,0,0,5,0,0,0
     ,0,0,0,0,0,7,7,0,0
    },
    { 0,0,0,5,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,8,0,0,0
    },
    { 0,0,0,5,0,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,9,0,0,0
    },
    { 0,0,0,5,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,10
     ,10,0,0,0,10,0,0,0
    },
    { 0,0,0,5,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0
     ,0,11,0,11,0,0,0
    },
    { 0,0,13,12,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,0,13,0,0,0,0,0,0
     ,14,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,0,0,0,12,20,0,0,0,5,0
     ,0,0,0,0,0,0,0,12,6,0,0
    },
    { 0,0,0,12,0,12,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13
     ,14,0,0,0,0,0,0,23,0,0,0,0,0,13,0,0,0,0,0,0,0,12,20,0,0,0,5
     ,0,0,0,0,0,0,0,0,13,13,0,0
    },
    { 0,0,19,14,0,12,0,0,0,0,0,0,0,0,14,0,17,15,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,0,0,0,14,20,0,0,0,5
     ,0,0,0,0,0,0,0,0,14,6,0,0
    },
    { 0,0,0,14,0,12,15,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,15
     ,14,0,0,0,0,0,0,23,0,0,0,16,0,15,0,0,15,0,0,0,0,14,20,0,0,16
     ,5,0,0,0,0,0,0,0,0,15,15,0,0
    },
    { 0,0,0,15,0,0,0,0,0,0,0,0,0,0,16,16,0,0,16,0,0,0,0,0,0,0,0,16
     ,0,0,0,0,0,0,0,0,0,0,0,16,0,16,0,0,0,0,0,0,0,15,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,16,0,0,0
    },
    { 0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,18,0,0,0,0,17,0,0,0,0,0,0,17
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,17,0,0,0,0,0,0,0,14,0,0,18,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,17,0,12,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18
     ,14,0,0,0,0,0,0,23,0,0,0,0,0,18,0,0,0,0,0,0,0,17,20,0,0,0,5
     ,0,0,0,0,0,0,0,0,18,18,0,0
    },
    { 0,0,0,14,0,12,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19
     ,14,0,0,0,0,0,0,23,0,0,0,0,0,19,0,0,0,0,0,0,0,14,20,0,0,0,5
     ,0,0,0,0,0,0,0,0,19,19,0,0
    },
    { 0,0,0,20,0,12,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,14,0,0,0,0,0,0,23,0,0,0,0,0,0,0,21,0,0,0,0,0,20,0,0,0,0,5,0
     ,0,0,0,0,0,0,0,20,6,0,0
    },
    { 0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,22,0,0,0,0,21,0,0,0,0,0,0,21
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,0,20,0,0,22,0,0,0
     ,0,0,0,0,0,0,0,21,0,0,0
    },
    { 0,0,0,21,0,12,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22
     ,14,0,0,0,0,0,0,23,0,0,0,0,0,22,0,0,0,0,0,0,0,21,20,0,0,0,5
     ,0,0,0,0,0,0,0,0,22,22,0,0
    },
    { 24,0,0,23,0,12,0,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,24,0,0,0,0,0
     ,14,24,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,20,0,0,0,5
     ,24,0,0,0,0,0,0,0,23,6,0,0
    },
    { 0,0,0,23,0,0,24,0,0,0,24,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,0,0,0,0,0,24
     ,0,0,0,0,0,0,24,0,0,0
    },
    { 0,0,0,3,0,0,25,25,0,0,0,25,0,0,0,27,0,0,0,28,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,26,0,0,0,0,0,0,25,25,0,0,25,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,25,0,0,26,0,0,0,0,0,0,0,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,26,0,0,0,0,0,0,0,0,0,26,26,0,0,26,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,27,0,0,0,0,0,0,0,0,0,0,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,27,0,0,0
    },
    { 0,0,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,28,28,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0
    },
    { 0,0,0,29,0,0,0,0,0,0,0,0,0,0,0,29,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,25,0,0,30,0,0,0,0,0,0,0,30,0,0,0,30,1,0,0
     ,0,0,0,30,30,0,0,0,0,0,0,0,2,0,0,0,0,30,30,2,0,0,0,0,0,0,0,0
     ,0,30,0,0,0,0,30,0,0,0,0
    }
};

static word _LR_action [31][67] =
{
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,5,0,0,3,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,7,0
    },
    { 0,0,0,9,12,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,8,0,0,0,0,0,0,10,0
     ,0,0,0,0,0,0,0,0,0,0,7,0,11,0,0,0,10,0,0,10,9,0,13,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0
    },
    { 0,25,18,14,0,27,0,0,0,0,0,0,0,24,16,0,0,0,0,0,0,0,0,20,0,0
     ,22,0,28,0,0,0,0,0,0,30,0,0,19,0,0,0,0,0,0,0,0,0,0,15,29,0,0
     ,0,0,0,0,0,0,0,23,0,0,17,26,0,21
    },
    { 0,0,0,14,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34
     ,39,0,0,0,0,0,0,41,0,0,0,0,0,35,0,0,0,0,0,0,0,31,40,0,0,0,36
     ,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 0,0,0,42,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34
     ,39,0,0,0,0,0,0,41,0,0,0,0,0,35,0,0,0,0,0,0,0,43,40,0,0,0,36
     ,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 0,0,0,42,0,0,0,0,0,0,0,0,0,0,45,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,44,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,46,0,0,0
    },
    { 0,0,0,42,0,0,0,0,0,0,0,0,0,0,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,49,0,0,0
    },
    { 0,0,0,42,0,0,0,0,0,0,0,0,0,0,51,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0,0,0,0,0,0,0,0
     ,54,53,0,0,0,52,0,0,0
    },
    { 0,0,0,42,0,0,0,0,0,0,0,0,0,0,56,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,55,0,0,0,0,0,0,0,0
     ,0,0,0,58,0,57,0,0,0
    },
    { 0,0,68,14,0,0,0,0,0,0,0,0,0,0,60,0,0,0,0,0,0,67,0,0,0,0,0,0
     ,64,0,0,0,0,0,0,66,0,0,0,0,0,0,0,0,0,0,0,0,0,59,65,0,0,0,62
     ,0,0,0,0,0,0,0,0,61,63,0,0
    },
    { 0,0,0,69,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34
     ,39,0,0,0,0,0,0,41,0,0,0,0,0,35,0,0,0,0,0,0,0,70,40,0,0,0,36
     ,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 0,0,81,14,0,76,0,0,0,0,0,0,0,0,72,0,80,79,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,78,0,0,0,0,0,0,0,0,0,0,0,0,0,71,77,0,0,0,74
     ,0,0,0,0,0,0,0,0,73,75,0,0
    },
    { 0,0,0,84,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,82,0,0,0,0,0,0,86
     ,39,0,0,0,0,0,0,41,0,0,0,83,0,87,0,0,88,0,0,0,0,85,40,0,0,89
     ,36,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 0,0,0,90,0,0,0,0,0,0,0,0,0,0,94,97,0,0,93,0,0,0,0,0,0,0,0,96
     ,0,0,0,0,0,0,0,0,0,0,0,91,0,98,0,0,0,0,0,0,0,92,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,95,0,0,0
    },
    { 0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,104,0,0,0,0,99,0,0,0,0,0,0
     ,102,0,0,0,0,0,0,0,0,0,0,0,0,0,103,0,0,0,0,0,0,0,101,0,0,105
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,106,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34
     ,39,0,0,0,0,0,0,41,0,0,0,0,0,35,0,0,0,0,0,0,0,107,40,0,0,0
     ,36,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 0,0,0,108,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34
     ,39,0,0,0,0,0,0,41,0,0,0,0,0,35,0,0,0,0,0,0,0,109,40,0,0,0
     ,36,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 0,0,0,14,0,115,0,0,0,0,0,0,0,0,111,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,116,0,0,0,0,0,0,117,0,0,0,0,0,0,0,118,0,0,0,0,0,110,0,0,0,0
     ,113,0,0,0,0,0,0,0,0,112,114,0,0
    },
    { 0,0,0,120,0,0,0,0,0,0,0,0,0,0,0,125,0,0,0,0,119,0,0,0,0,0,0
     ,123,0,0,0,0,0,0,0,0,0,0,0,0,0,124,0,0,0,0,0,0,0,121,0,0,126
     ,0,0,0,0,0,0,0,0,0,0,122,0,0,0
    },
    { 0,0,0,127,0,38,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,129,39,0,0,0,0,0,0,41,0,0,0,0,0,130,0,0,0,0,0,0,0,128,40,0
     ,0,0,36,0,0,0,0,0,0,0,0,33,37,0,0
    },
    { 140,0,0,14,0,136,0,0,0,0,0,0,0,0,132,0,0,0,0,0,0,0,141,0,0,0
     ,0,0,137,143,142,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,138
     ,0,0,0,134,139,0,0,0,0,0,0,0,133,135,0,0
    },
    { 0,0,0,144,0,0,150,0,0,0,149,0,0,0,147,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,145,0,0,0,0,0
     ,0,146,0,0,0,0,0,0,148,0,0,0
    },
    { 0,0,0,6,0,0,151,154,0,0,0,155,0,0,0,153,0,0,0,157,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,156,0,0,0,0,0,0,152,152,0,0,152,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,158,0,0,159,0,0,0,0,0,0,0,0,153,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,161,0,0,0,0,0,0,0,0,0,160,160,0,0,160,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,14,0,0,0,0,0,0,0,0,0,0,163,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,162,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,164,0,0,0
    },
    { 0,0,0,158,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,165,165,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,166,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,173,0,0,169,0,0,0,0,0,0,0,171,0,0,0,169
     ,172,0,0,0,0,0,175,169,0,0,0,0,0,0,0,168,0,0,0,0,169,167,174
     ,0,0,0,0,0,0,0,0,0,170,0,0,0,0,1,0,0,0,0
    }
};

static word _LR_offset [] =
{
    0,
    0,
    1,
    4,
    8,
    15,
    20,
    25,
    30,
    32,
    35,
    38,
    41,
    48,
    54,
    58,
    63,
    66,
    69,
    74,
    79,
    84,
    89,
    94,
    99,
    104,
    109,
    115,
    121,
    127,
    133,
    139,
    145,
    149,
    152,
    157,
    162,
    169,
    176,
    183,
    190,
    197,
    204,
    208,
    214,
    219,
    222,
    225,
    230,
    233,
    236,
    241,
    244,
    247,
    251,
    255,
    260,
    263,
    266,
    271,
    276,
    279,
    282,
    288,
    294,
    300,
    306,
    312,
    317,
    322,
    326,
    332,
    337,
    340,
    343,
    349,
    355,
    361,
    367,
    373,
    378,
    383,
    388,
    390,
    394,
    399,
    404,
    407,
    410,
    413,
    417,
    421,
    424,
    429,
    433,
    436,
    439,
    443,
    447,
    451,
    453,
    458,
    463,
    466,
    469,
    474,
    478,
    482,
    488,
    492,
    498,
    503,
    506,
    509,
    515,
    521,
    527,
    533,
    539,
    544,
    546,
    551,
    557,
    560,
    564,
    568,
    574,
    578,
    582,
    587,
    591,
    595,
    600,
    603,
    606,
    612,
    618,
    624,
    630,
    636,
    642,
    648,
    654,
    660,
    666,
    670,
    675,
    678,
    681,
    684,
    687,
    690,
    694,
    697,
    704,
    708,
    712,
    716,
    720,
    724,
    728,
    731,
    735,
    741,
    744,
    747,
    750,
    755,
    758,
    761,
    764,
    767,
    769,
    772,
    777,
    782
};

static word _LR_vector [] =
{
    _LR_STOP,
    0,1,_LR_STOP,
    2,3,4,_LR_STOP,
    5,6,7,8,4,9,_LR_STOP,
    10,11,4,9,_LR_STOP,
    12,2,3,4,_LR_STOP,
    13,14,4,9,_LR_STOP,
    15,_LR_STOP,
    16,17,_LR_STOP,
    11,4,_LR_STOP,
    18,4,_LR_STOP,
    19,6,7,8,4,9,_LR_STOP,
    6,7,8,4,9,_LR_STOP,
    20,16,17,_LR_STOP,
    21,22,16,17,_LR_STOP,
    23,4,_LR_STOP,
    8,4,_LR_STOP,
    21,24,25,4,_LR_STOP,
    21,26,25,4,_LR_STOP,
    21,27,28,4,_LR_STOP,
    21,29,25,4,_LR_STOP,
    21,30,25,4,_LR_STOP,
    21,31,32,4,_LR_STOP,
    21,33,34,4,_LR_STOP,
    21,35,36,4,_LR_STOP,
    21,16,37,25,4,_LR_STOP,
    21,16,38,39,4,_LR_STOP,
    21,16,40,41,4,_LR_STOP,
    21,16,42,43,4,_LR_STOP,
    21,16,44,45,4,_LR_STOP,
    46,47,22,16,17,_LR_STOP,
    48,49,4,_LR_STOP,
    25,4,_LR_STOP,
    46,47,25,4,_LR_STOP,
    46,47,50,4,_LR_STOP,
    46,47,16,7,8,4,_LR_STOP,
    46,47,16,37,25,4,_LR_STOP,
    46,47,16,38,39,4,_LR_STOP,
    46,47,16,40,41,4,_LR_STOP,
    46,47,16,42,43,4,_LR_STOP,
    46,47,16,44,45,4,_LR_STOP,
    16,8,4,_LR_STOP,
    46,47,16,8,4,_LR_STOP,
    51,16,8,4,_LR_STOP,
    52,4,_LR_STOP,
    28,4,_LR_STOP,
    53,16,8,4,_LR_STOP,
    54,4,_LR_STOP,
    32,4,_LR_STOP,
    55,16,8,4,_LR_STOP,
    56,4,_LR_STOP,
    34,4,_LR_STOP,
    57,49,4,_LR_STOP,
    58,49,4,_LR_STOP,
    59,16,8,4,_LR_STOP,
    60,4,_LR_STOP,
    36,4,_LR_STOP,
    59,61,49,4,_LR_STOP,
    62,22,16,17,_LR_STOP,
    63,4,_LR_STOP,
    39,4,_LR_STOP,
    62,16,7,8,4,_LR_STOP,
    62,16,37,25,4,_LR_STOP,
    62,16,40,41,4,_LR_STOP,
    62,16,42,43,4,_LR_STOP,
    62,16,44,45,4,_LR_STOP,
    62,64,25,4,_LR_STOP,
    62,65,25,4,_LR_STOP,
    16,39,4,_LR_STOP,
    46,47,16,39,4,_LR_STOP,
    66,22,16,17,_LR_STOP,
    67,4,_LR_STOP,
    41,4,_LR_STOP,
    66,16,7,8,4,_LR_STOP,
    66,16,37,25,4,_LR_STOP,
    66,16,38,39,4,_LR_STOP,
    66,16,42,43,4,_LR_STOP,
    66,16,44,45,4,_LR_STOP,
    66,68,69,4,_LR_STOP,
    66,70,71,4,_LR_STOP,
    66,72,25,4,_LR_STOP,
    73,_LR_STOP,
    74,75,4,_LR_STOP,
    76,16,41,4,_LR_STOP,
    77,16,41,4,_LR_STOP,
    69,4,_LR_STOP,
    78,4,_LR_STOP,
    79,4,_LR_STOP,
    74,80,4,_LR_STOP,
    16,69,4,_LR_STOP,
    75,4,_LR_STOP,
    81,16,69,4,_LR_STOP,
    82,83,4,_LR_STOP,
    84,4,_LR_STOP,
    80,4,_LR_STOP,
    81,85,4,_LR_STOP,
    86,49,4,_LR_STOP,
    81,87,4,_LR_STOP,
    88,_LR_STOP,
    89,16,41,4,_LR_STOP,
    90,16,41,4,_LR_STOP,
    71,4,_LR_STOP,
    91,4,_LR_STOP,
    92,93,25,4,_LR_STOP,
    93,25,4,_LR_STOP,
    16,94,4,_LR_STOP,
    46,95,16,94,4,_LR_STOP,
    16,41,4,_LR_STOP,
    46,47,16,41,4,_LR_STOP,
    96,22,16,17,_LR_STOP,
    97,4,_LR_STOP,
    43,4,_LR_STOP,
    96,16,7,8,4,_LR_STOP,
    96,16,37,25,4,_LR_STOP,
    96,16,38,39,4,_LR_STOP,
    96,16,40,41,4,_LR_STOP,
    96,16,44,45,4,_LR_STOP,
    96,98,99,4,_LR_STOP,
    100,_LR_STOP,
    76,16,43,4,_LR_STOP,
    101,77,16,43,4,_LR_STOP,
    99,4,_LR_STOP,
    101,99,4,_LR_STOP,
    101,102,4,_LR_STOP,
    101,103,104,25,4,_LR_STOP,
    104,25,4,_LR_STOP,
    16,105,4,_LR_STOP,
    106,16,105,4,_LR_STOP,
    47,25,4,_LR_STOP,
    47,50,4,_LR_STOP,
    107,22,16,17,_LR_STOP,
    108,4,_LR_STOP,
    45,4,_LR_STOP,
    107,16,7,8,4,_LR_STOP,
    107,16,37,25,4,_LR_STOP,
    107,16,38,39,4,_LR_STOP,
    107,16,40,41,4,_LR_STOP,
    107,16,42,43,4,_LR_STOP,
    107,109,110,111,4,_LR_STOP,
    107,109,112,111,4,_LR_STOP,
    107,109,113,111,4,_LR_STOP,
    107,109,114,111,4,_LR_STOP,
    107,109,115,111,4,_LR_STOP,
    16,45,4,_LR_STOP,
    116,16,45,4,_LR_STOP,
    117,4,_LR_STOP,
    118,4,_LR_STOP,
    111,4,_LR_STOP,
    119,4,_LR_STOP,
    120,4,_LR_STOP,
    121,122,4,_LR_STOP,
    122,4,_LR_STOP,
    5,6,123,124,4,9,_LR_STOP,
    125,122,4,_LR_STOP,
    126,122,4,_LR_STOP,
    127,128,4,_LR_STOP,
    129,130,4,_LR_STOP,
    16,122,4,_LR_STOP,
    131,128,4,_LR_STOP,
    128,4,_LR_STOP,
    132,128,4,_LR_STOP,
    133,22,134,16,17,_LR_STOP,
    135,4,_LR_STOP,
    124,4,_LR_STOP,
    130,4,_LR_STOP,
    136,137,16,17,_LR_STOP,
    138,4,_LR_STOP,
    12,1,_LR_STOP,
    49,4,_LR_STOP,
    12,139,_LR_STOP,
    140,_LR_STOP,
    12,141,_LR_STOP,
    12,142,122,4,_LR_STOP,
    12,143,0,1,_LR_STOP,
    12,144,139,_LR_STOP
};

static HOOK *_LR_module [145] = {
    decode_http_initial_request,
    determine_initial_screen,
    open_main_admin_menu,
    show_main_admin_menu,
    decode_http_request_reponse,
    use_defaults_config_name,
    load_current_config_file,
    open_config_server,
    show_config_server,
    dialog_call,
    open_config_list,
    show_config_list_first,
    close_all_forms,
    open_vhost_wizard,
    show_vhost_wizard,
    check_config_list_livelink,
    close_current_form,
    dialog_return,
    show_config_list_next,
    use_basehost_config_name,
    cancel_current_config_file,
    update_config_server,
    save_current_config_file,
    show_config_server_defaults,
    open_config_aliases,
    show_config_value_list_first,
    open_config_mimes,
    open_config_errors,
    show_config_errors,
    open_config_wsx,
    open_config_filter,
    open_config_ssi,
    show_config_ssi,
    open_config_ddns,
    show_config_ddns,
    open_config_advanced,
    show_config_advanced,
    open_config_vhosts,
    open_config_cgi,
    show_config_cgi,
    open_config_ftp,
    show_config_ftp,
    open_config_security,
    show_config_security,
    open_config_logging,
    show_config_logging,
    validate_config_value_list,
    update_config_value_list,
    clear_config_value_list,
    reshow_current_form,
    show_config_value_list_next,
    update_config_errors,
    show_config_errors_defaults,
    update_config_ssi,
    show_config_ssi_defaults,
    update_config_ddns,
    show_config_ddns_defaults,
    send_signon_to_ddns_agent,
    send_signoff_to_ddns_agent,
    update_config_advanced,
    show_config_advanced_defaults,
    test_url_mapping,
    update_config_cgi,
    show_config_cgi_defaults,
    open_config_cgi_envir,
    open_config_cgi_alias,
    update_config_ftp,
    show_config_ftp_defaults,
    open_config_ftp_users,
    show_config_ftp_users_first,
    open_config_ftp_dirs,
    show_config_ftp_dirs_first,
    open_config_ftp_alias,
    check_ftp_users_livelink,
    open_config_ftp_user,
    show_config_ftp_user_new,
    cancel_config_resource_file,
    save_config_resource_file,
    show_config_ftp_users_next,
    show_config_ftp_users_same,
    show_config_ftp_user,
    update_config_ftp_user,
    delete_config_ftp_user,
    show_config_ftp_user_same,
    show_config_ftp_user_defaults,
    show_config_ftp_user_first,
    set_permissions_as_chosen,
    show_config_ftp_user_next,
    check_ftp_dir_livelink,
    cancel_config_ftp_dir_file,
    save_config_ftp_dir_file,
    show_config_ftp_dirs_next,
    check_new_ftp_dir_name,
    open_config_ftp_user_list,
    show_config_ftp_dirs_same,
    update_config_ftp_user_list,
    update_config_security,
    show_config_security_defaults,
    open_config_resources,
    show_config_resources_first,
    check_resources_livelink,
    update_config_resources,
    show_config_resources_next,
    check_new_resource_name,
    open_config_user_list,
    show_config_resources_same,
    update_config_user_list,
    update_config_logging,
    show_config_logging_defaults,
    open_config_log_file,
    choose_server_log,
    show_log_file_details,
    choose_http_access_log,
    choose_http_error_log,
    choose_ftp_access_log,
    choose_ftp_error_log,
    update_log_file_details,
    show_log_file_format,
    show_log_file_defaults,
    cycle_log_file_if_possible,
    clear_log_file_if_possible,
    clear_console_panel_statistics,
    show_console_panel,
    open_console_config,
    show_console_config,
    clear_all_active_logfiles,
    cycle_all_active_logfiles,
    open_console_messages,
    show_console_messages,
    open_connection_list,
    show_connection_list,
    clear_console_messages,
    invert_console_data,
    update_console_config,
    reload_server_base_config,
    show_console_config_defaults,
    validate_vhost_definition,
    create_vhost_definition,
    send_resource_file_if_known,
    terminate_the_thread,
    check_simple_livelink,
    redirect_to_home_page,
    open_console_panel,
    restart_http_server_agent,
    shutdown_http_server_agent
};

#if (defined (DEBUG))
static char *_LR_mname [145] =
{
     "Decode-Http-Initial-Request",
     "Determine-Initial-Screen",
     "Open-Main-Admin-Menu",
     "Show-Main-Admin-Menu",
     "Decode-Http-Request-Reponse",
     "Use-Defaults-Config-Name",
     "Load-Current-Config-File",
     "Open-Config-Server",
     "Show-Config-Server",
     "Dialog-Call",
     "Open-Config-List",
     "Show-Config-List-First",
     "Close-All-Forms",
     "Open-Vhost-Wizard",
     "Show-Vhost-Wizard",
     "Check-Config-List-Livelink",
     "Close-Current-Form",
     "Dialog-Return",
     "Show-Config-List-Next",
     "Use-Basehost-Config-Name",
     "Cancel-Current-Config-File",
     "Update-Config-Server",
     "Save-Current-Config-File",
     "Show-Config-Server-Defaults",
     "Open-Config-Aliases",
     "Show-Config-Value-List-First",
     "Open-Config-Mimes",
     "Open-Config-Errors",
     "Show-Config-Errors",
     "Open-Config-Wsx",
     "Open-Config-Filter",
     "Open-Config-Ssi",
     "Show-Config-Ssi",
     "Open-Config-Ddns",
     "Show-Config-Ddns",
     "Open-Config-Advanced",
     "Show-Config-Advanced",
     "Open-Config-Vhosts",
     "Open-Config-Cgi",
     "Show-Config-Cgi",
     "Open-Config-Ftp",
     "Show-Config-Ftp",
     "Open-Config-Security",
     "Show-Config-Security",
     "Open-Config-Logging",
     "Show-Config-Logging",
     "Validate-Config-Value-List",
     "Update-Config-Value-List",
     "Clear-Config-Value-List",
     "Reshow-Current-Form",
     "Show-Config-Value-List-Next",
     "Update-Config-Errors",
     "Show-Config-Errors-Defaults",
     "Update-Config-Ssi",
     "Show-Config-Ssi-Defaults",
     "Update-Config-Ddns",
     "Show-Config-Ddns-Defaults",
     "Send-Signon-To-Ddns-Agent",
     "Send-Signoff-To-Ddns-Agent",
     "Update-Config-Advanced",
     "Show-Config-Advanced-Defaults",
     "Test-Url-Mapping",
     "Update-Config-Cgi",
     "Show-Config-Cgi-Defaults",
     "Open-Config-Cgi-Envir",
     "Open-Config-Cgi-Alias",
     "Update-Config-Ftp",
     "Show-Config-Ftp-Defaults",
     "Open-Config-Ftp-Users",
     "Show-Config-Ftp-Users-First",
     "Open-Config-Ftp-Dirs",
     "Show-Config-Ftp-Dirs-First",
     "Open-Config-Ftp-Alias",
     "Check-Ftp-Users-Livelink",
     "Open-Config-Ftp-User",
     "Show-Config-Ftp-User-New",
     "Cancel-Config-Resource-File",
     "Save-Config-Resource-File",
     "Show-Config-Ftp-Users-Next",
     "Show-Config-Ftp-Users-Same",
     "Show-Config-Ftp-User",
     "Update-Config-Ftp-User",
     "Delete-Config-Ftp-User",
     "Show-Config-Ftp-User-Same",
     "Show-Config-Ftp-User-Defaults",
     "Show-Config-Ftp-User-First",
     "Set-Permissions-As-Chosen",
     "Show-Config-Ftp-User-Next",
     "Check-Ftp-Dir-Livelink",
     "Cancel-Config-Ftp-Dir-File",
     "Save-Config-Ftp-Dir-File",
     "Show-Config-Ftp-Dirs-Next",
     "Check-New-Ftp-Dir-Name",
     "Open-Config-Ftp-User-List",
     "Show-Config-Ftp-Dirs-Same",
     "Update-Config-Ftp-User-List",
     "Update-Config-Security",
     "Show-Config-Security-Defaults",
     "Open-Config-Resources",
     "Show-Config-Resources-First",
     "Check-Resources-Livelink",
     "Update-Config-Resources",
     "Show-Config-Resources-Next",
     "Check-New-Resource-Name",
     "Open-Config-User-List",
     "Show-Config-Resources-Same",
     "Update-Config-User-List",
     "Update-Config-Logging",
     "Show-Config-Logging-Defaults",
     "Open-Config-Log-File",
     "Choose-Server-Log",
     "Show-Log-File-Details",
     "Choose-Http-Access-Log",
     "Choose-Http-Error-Log",
     "Choose-Ftp-Access-Log",
     "Choose-Ftp-Error-Log",
     "Update-Log-File-Details",
     "Show-Log-File-Format",
     "Show-Log-File-Defaults",
     "Cycle-Log-File-If-Possible",
     "Clear-Log-File-If-Possible",
     "Clear-Console-Panel-Statistics",
     "Show-Console-Panel",
     "Open-Console-Config",
     "Show-Console-Config",
     "Clear-All-Active-Logfiles",
     "Cycle-All-Active-Logfiles",
     "Open-Console-Messages",
     "Show-Console-Messages",
     "Open-Connection-List",
     "Show-Connection-List",
     "Clear-Console-Messages",
     "Invert-Console-Data",
     "Update-Console-Config",
     "Reload-Server-Base-Config",
     "Show-Console-Config-Defaults",
     "Validate-Vhost-Definition",
     "Create-Vhost-Definition",
     "Send-Resource-File-If-Known",
     "Terminate-The-Thread",
     "Check-Simple-Livelink",
     "Redirect-To-Home-Page",
     "Open-Console-Panel",
     "Restart-Http-Server-Agent",
     "Shutdown-Http-Server-Agent"
};

static char *_LR_sname [31] =
{
     "After-Init",
     "Start-Session",
     "Select-Initial",
     "Main-Menu",
     "Config-List",
     "Config-Server",
     "Config-Value-List",
     "Config-Server-List",
     "Config-Errors",
     "Config-Ssi",
     "Config-Ddns",
     "Config-Advanced",
     "Config-Cgi",
     "Config-Cgi-Sub-List",
     "Config-Ftp",
     "Config-Ftp-Users",
     "Config-Ftp-User",
     "Config-Ftp-Dirs",
     "Config-Ftp-User-List",
     "Config-Ftp-Sub-List",
     "Config-Security",
     "Config-Resources",
     "Config-User-List",
     "Config-Logging",
     "Config-Log-File",
     "Console-Panel",
     "Console-Messages",
     "Console-Config",
     "Connection-List",
     "Vhost-Wizard",
     "Defaults"
};

static char *_LR_ename [67] =
{
     "Accesslog-Event",
     "Advanced-Event",
     "Aliases-Event",
     "Back-Event",
     "Basehost-Event",
     "Cgi-Event",
     "Clear-Event",
     "Clear-Logs-Event",
     "Config-Event",
     "Console-Event",
     "Cycle-Event",
     "Cycle-Logs-Event",
     "Data-Error-Event",
     "Ddns-Event",
     "Default-Event",
     "Define-Event",
     "Define-Dirs-Event",
     "Define-Users-Event",
     "Delete-Event",
     "Details-Event",
     "Enter-Event",
     "Environment-Event",
     "Errorlog-Event",
     "Errors-Event",
     "Exception-Event",
     "Exit-Event",
     "Filters-Event",
     "First-Event",
     "Ftp-Event",
     "Ftperrors-Event",
     "Ftplog-Event",
     "Halt-Event",
     "Help-Event",
     "Hosts-Event",
     "Invert-Event",
     "Logging-Event",
     "Main-Event",
     "Messages-Event",
     "Mimes-Event",
     "New-Event",
     "New-Session-Event",
     "Next-Event",
     "Ok-Event",
     "Passwords-Event",
     "Refresh-Event",
     "Reshow-Form-Event",
     "Resource-Event",
     "Restart-Event",
     "Return-Event",
     "Save-Event",
     "Security-Event",
     "Select-Config-Event",
     "Select-Resource-Event",
     "Select-User-Event",
     "Server-Event",
     "Serverlog-Event",
     "Show-Event",
     "Shutdown-Event",
     "Signoff-Event",
     "Signon-Event",
     "Ssi-Event",
     "Test-Event",
     "Timeout-Event",
     "Undo-Event",
     "Vhosts-Event",
     "Wizard-Event",
     "Wsx-Event"
};
#else
static char *_LR_mname [145] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33",
     "34",
     "35",
     "36",
     "37",
     "38",
     "39",
     "40",
     "41",
     "42",
     "43",
     "44",
     "45",
     "46",
     "47",
     "48",
     "49",
     "50",
     "51",
     "52",
     "53",
     "54",
     "55",
     "56",
     "57",
     "58",
     "59",
     "60",
     "61",
     "62",
     "63",
     "64",
     "65",
     "66",
     "67",
     "68",
     "69",
     "70",
     "71",
     "72",
     "73",
     "74",
     "75",
     "76",
     "77",
     "78",
     "79",
     "80",
     "81",
     "82",
     "83",
     "84",
     "85",
     "86",
     "87",
     "88",
     "89",
     "90",
     "91",
     "92",
     "93",
     "94",
     "95",
     "96",
     "97",
     "98",
     "99",
     "100",
     "101",
     "102",
     "103",
     "104",
     "105",
     "106",
     "107",
     "108",
     "109",
     "110",
     "111",
     "112",
     "113",
     "114",
     "115",
     "116",
     "117",
     "118",
     "119",
     "120",
     "121",
     "122",
     "123",
     "124",
     "125",
     "126",
     "127",
     "128",
     "129",
     "130",
     "131",
     "132",
     "133",
     "134",
     "135",
     "136",
     "137",
     "138",
     "139",
     "140",
     "141",
     "142",
     "143",
     "144"
};

static char *_LR_sname [31] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30"
};

static char *_LR_ename [67] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33",
     "34",
     "35",
     "36",
     "37",
     "38",
     "39",
     "40",
     "41",
     "42",
     "43",
     "44",
     "45",
     "46",
     "47",
     "48",
     "49",
     "50",
     "51",
     "52",
     "53",
     "54",
     "55",
     "56",
     "57",
     "58",
     "59",
     "60",
     "61",
     "62",
     "63",
     "64",
     "65",
     "66"
};
#endif

MODULE dialog_call (THREAD *thread)
{
    if (thread-> LR_stack_size < 20)
        thread-> LR_stack [thread-> LR_stack_size++] = thread-> LR_state;
    else
      {
        fprintf (stdout,
            "State %d - Dialog-Call overflow\n", thread-> LR_state);
        exit (EXIT_FAILURE);
      }
}

MODULE dialog_return (THREAD *thread)
{
    if (thread-> LR_stack_size > 0)
      {
        thread-> LR_state = thread-> LR_stack [--(thread-> LR_stack_size)];
        raise_exception (return_event);
      }
    else
      {
        fprintf (stdout,
            "State %d - Dialog-Return underflow\n", thread-> LR_state);
        exit (EXIT_FAILURE);
      }
}
