/*==========================================================
 *                                                          
 *  version.h - version information for Xitami/Open          
 *                                                          
 *  Should be the last file included in parent source program.
 *  This file is generated by Boom at configuration time.   
 *  Copyright (c) 1991-2003 iMatix Corporation
 *==========================================================*/

#undef  VERSION         /*  Scrap any previous definitions  */
#undef  PRODUCT         
#undef  COPYRIGHT       
#undef  BUILDDATE       
#undef  BUILDMODEL      
#define VERSION         "2.5c2"
#define PRODUCT         "Xitami/Open/2.5c2"
#define COPYRIGHT       "Copyright (c) 1991-2003 iMatix Corporation"
#define BUILDDATE       "2004/07/22 17:51:37"
#define BUILDMODEL      "Debug release for internal use only"
/*  Embed the version information in the resulting binary   */
char *xit_version_start = "VeRsIoNsTaRt:xit";
char *xit_version = VERSION;
char *xit_product = PRODUCT;
char *xit_copyright = COPYRIGHT;
char *xit_builddate = BUILDDATE;
char *xit_buildmodel = BUILDMODEL;
char *xit_version_end = "VeRsIoNeNd:xit";
