/*---------------------------------------------------------------------------*
 *  brocgi.d - LIBERO dialog data definitions for brocgi.c.                  *
 *  Generated by LIBERO 2.4 on 22 Jul, 2004, 16:52.                          *
 *  Schema file used: lrschema.c.                                            *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
enum {
    terminate_event = -1,
    call_event = 0,
    call_failed_event = 1,
    error_event = 2,
    exception_event = 3,
    file_io_error_event = 4,
    finished_event = 5,
    in_progress_event = 6,
    new_session_event = 7,
    ok_event = 8,
    out_of_step_event = 9,
    return_event = 10,
    show_event = 11,
    timed_out_event = 12
};

enum {
    _LR_defaults_state = 3,
    _LR_STATE_after_init = 0,
    _LR_STATE_have_session = 1,
    _LR_STATE_after_program = 2,
    _LR_STATE_defaults = 3
};


/*- Variables used by dialog interpreter ------------------------------------*/

typedef int event_t;                    /*  Type for dialog entity           */
typedef void (fsmfunct) (void);         /*  Address of FSM function          */

static event_t
    _LR_event,                          /*  Event for state transition       */
    _LR_state,                          /*  Current dialog state             */
    _LR_savest,                         /*  Saved dialog state               */
    _LR_index,                          /*  Index into vector table          */
    the_next_event,                     /*  Next event from module           */
    the_exception_event;                /*  Exception event from module      */

static dbyte
   *_LR_vecptr;                         /*  Pointer into vector table        */

static Bool
    exception_raised;                   /*  TRUE if exception raised         */

/*- Function prototypes -----------------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

local  raise_exception                  (event_t event);
MODULE initialise_the_program           (void);
MODULE get_external_event               (void);
MODULE cleanup_old_sessions             (void);
MODULE initialise_session_data          (void);
MODULE parse_arguments_if_any           (void);
MODULE check_if_new_session             (void);
MODULE terminate_the_program            (void);
MODULE prepare_new_session              (void);
MODULE set_initial_program              (void);
MODULE init_program_context             (void);
MODULE start_the_transaction            (void);
MODULE invoke_active_program            (void);
MODULE try_to_restore_context           (void);
MODULE load_program_context             (void);
MODULE signal_session_timed_out         (void);
MODULE signal_invalid_session           (void);
MODULE send_html_form_to_client         (void);
MODULE save_program_context             (void);
MODULE save_session_context             (void);
MODULE end_the_transaction              (void);
MODULE push_new_active_program          (void);
MODULE check_program_not_active         (void);
MODULE close_program_context            (void);
MODULE pop_old_active_program           (void);
MODULE delete_session_context           (void);
MODULE signal_file_io_error             (void);

/*- Static areas ------------------------------------------------------------*/

static dbyte _LR_nextst [][13] =
{
    { 0,0,0,0,0,0,0,0,1,0,0,0,0 },
    { 0,0,0,0,0,0,2,2,0,1,0,0,1 },
    { 2,2,0,0,0,2,0,0,0,0,2,2,0 },
    { 0,0,0,3,3,0,0,0,0,0,0,0,0 }
};

static dbyte _LR_action [][13] =
{
    { 0,0,2,0,0,0,0,0,1,0,0,0,0 },
    { 0,0,0,0,0,0,4,3,0,6,0,0,5 },
    { 8,9,0,0,0,10,0,0,0,0,9,7,0 },
    { 0,0,0,11,12,0,0,0,0,0,0,0,0 }
};

static dbyte _LR_vector [][5+1] =
{
    {0},
    {0,1,2,3,_LR_STOP},
    {4,_LR_STOP},
    {5,6,7,8,9,_LR_STOP},
    {10,11,8,9,_LR_STOP},
    {12,4,_LR_STOP},
    {13,4,_LR_STOP},
    {14,15,16,17,4,_LR_STOP},
    {15,18,7,19,9,_LR_STOP},
    {20,21,11,9,_LR_STOP},
    {6,7,9,_LR_STOP},
    {22,4,_LR_STOP},
    {23,4,_LR_STOP}
};

static fsmfunct *_LR_module [] =
{
    cleanup_old_sessions,
    initialise_session_data,
    parse_arguments_if_any,
    check_if_new_session,
    terminate_the_program,
    prepare_new_session,
    set_initial_program,
    init_program_context,
    start_the_transaction,
    invoke_active_program,
    try_to_restore_context,
    load_program_context,
    signal_session_timed_out,
    signal_invalid_session,
    send_html_form_to_client,
    save_program_context,
    save_session_context,
    end_the_transaction,
    push_new_active_program,
    check_program_not_active,
    close_program_context,
    pop_old_active_program,
    delete_session_context,
    signal_file_io_error
};

