/*==========================================================
 *                                                          
 *  version.h - version information for GSL                  
 *                                                          
 *  Should be the last file included in parent source program.
 *  This file is generated by Boom at configuration time.   
 *  Copyright (c) 1991-2003 iMatix Corporation
 *==========================================================*/

#undef  VERSION         /*  Scrap any previous definitions  */
#undef  PRODUCT         
#undef  COPYRIGHT       
#undef  BUILDDATE       
#undef  BUILDMODEL      
#define VERSION         "2.01"
#define PRODUCT         "GSL/2.01"
#define COPYRIGHT       "Copyright (c) 1991-2003 iMatix Corporation"
#define BUILDDATE       "2004/07/22 17:51:37"
#define BUILDMODEL      "Debug release for internal use only"
/*  Embed the version information in the resulting binary   */
char *gsl_version_start = "VeRsIoNsTaRt:gsl";
char *gsl_version = VERSION;
char *gsl_product = PRODUCT;
char *gsl_copyright = COPYRIGHT;
char *gsl_builddate = BUILDDATE;
char *gsl_buildmodel = BUILDMODEL;
char *gsl_version_end = "VeRsIoNeNd:gsl";
